# -*- coding: utf-8 -*-
"""Prodigy_ML_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGXrC9SeMim8S2_c-vmKCUraEJsdJMy9
"""

from google.colab import files

# Upload the CSV file
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load the training dataset
train_data = pd.read_csv('train.csv')

# Load the test dataset
test_data = pd.read_csv('test.csv')

# Select features and target variable
features = ['GrLivArea', 'BedroomAbvGr', 'FullBath']
target = 'SalePrice'
X_train = train_data[features]
y_train = train_data[target]
X_test = test_data[features]  # Assuming the test set has the same features as the training set

# Create and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Create a DataFrame to display the predictions alongside the corresponding features
predictions_df = pd.DataFrame({
    'Id': test_data['Id'],
    'GrLivArea': X_test['GrLivArea'],
    'BedroomAbvGr': X_test['BedroomAbvGr'],
    'FullBath': X_test['FullBath'],
    'Predicted_SalePrice': y_pred
})

# Display the predictions
print(predictions_df.head())